name: "Check Online Version"
on:
  workflow_dispatch:
  schedule:
  - cron: "0 0 * * *"

jobs:
  get_versions:
    name: Get Versions
    runs-on: ubuntu-latest
    outputs:
      current_version: ${{ steps.current_version.outputs.version }}
      latest_version: ${{ steps.latest_version.outputs.version }}

    steps:
    - name: Get Current Release
      uses: octokit/request-action@v2.x
      id: repo_latest_release
      with:
        route: GET /repos/{owner}/{repo}/releases/latest
        owner: requarks
        repo: wiki
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    
    - name: Set Current Release
      id: latest_version
      run: |
        echo "::set-output name=version::$(echo '${{ steps.repo_latest_release.outputs.data }}' | jq -r '.tag_name')"

    - name: Get repository name
      id: repo_name
      run: echo "::set-output name=repository::$(echo ${{ github.repository }} | cut -d'/' -f 2)"
                
    - name: Get Docker version
      uses: octokit/request-action@v2.x
      id: docker_version
      with:
        route: GET /orgs/{org}/packages/{package_type}/{package_name}/versions
        org: ${{ github.repository_owner }}
        package_type: container
        package_name: wikijs
        per_page: 1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Set Docker versions
      id: current_version
      run: |
        echo "::set-output name=version::$(echo '${{ steps.docker_version.outputs.data }}' | jq -r '.[0].metadata.container.tags[]|select(startswith("v"))')"

  update-version-txt:
    name: Update version.txt
    runs-on: ubuntu-latest
    needs: get_versions
    if: needs.get_versions.outputs.latest_version != needs.get_versions.outputs.current_version
    steps:
    - uses: actions/checkout@v3
    - run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        echo -e "${{ needs.get_versions.outputs.latest_version }}" > ./manifest/version.txt
        git commit -a -m "Bump version.txt"
        git push

  request_build:
    name: Request Build
    runs-on: ubuntu-latest
    needs:
    - get_versions
    - update-version-txt
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - uses: ./.github/workflows/update.yml
