name: Update Image

on:
  workflow_dispatch:
  workflow_call:
jobs:
  build_push:
    name: Build and Push Container
    runs-on: ubuntu-latest
    steps:
    - name: Clone repo
      uses: actions/checkout@v3

    - name: Clone Wiki.js repo
      uses: actions/checkout@v3
      with:
        repository: requarks/wiki
        path: wikijs

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Read version and replace Dockerfile
      id: read_version
      run: |
        echo "::set-output name=version::$(cat ./manifest/version.txt)"
        cp ./manifest/images/Dockerfile ./wikijs/dev/build/Dockerfile

    - name: Disable DEV Flag + Set Version
      working-directory: ./wikijs
      run: |
        sudo apt-get install jq -y
        mv package.json pkg-temp.json
        jq --arg vs "${{ steps.read_version.outputs.version }}" -r '. + {dev:false, version:$vs}' pkg-temp.json > package.json
        rm pkg-temp.json
        cat package.json

    - name: Docker meta
      id: docker_meta
      uses: docker/metadata-action@v3
      with:
        images: ghcr.io/${{ github.repository_owner }}/wikijs
        flavor: |
          latest=auto
        tags: |
          type=raw,value=${{ steps.read_version.outputs.version }}
          type=raw,value=latest

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: ./wikijs
        file: ./manifest/images/Dockerfile
        platforms: linux/amd64
        push: true
        tags: ${{ steps.docker_meta.outputs.tags }}
        labels: ${{ steps.docker_meta.outputs.labels }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=local,dest=/tmp/.buildx-cache
